name: categorifier
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - "ghc8107"
          - "ghc884"
          - "ghc901"
          - "ghc921"
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout repositiory code
      uses: actions/checkout@v3
    - name: List files
      run: |
        ls ${{ github.workspace }}
    - name: build
      run: |
        nix build --print-build-logs .#${{ matrix.ghc }}_categorifier-category
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v5
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rwe/actions-hlint-setup@v1
        with:
          version: '3.3.6'
      - uses: rwe/actions-hlint-run@v2
        with:
          path: '["category/", "client/", "common/", "duoids/", "hedgehog/", "plugin/"]'
          fail-on: status
